### ISSUE TITLE
Cannot open on OSX Big Sur

### ISSUE THREAD

**Issue by neamtua** [beyondcode/laravel-debugbar-companion#2]
When I try to launch the app it says "You do not have permission to open the application "Laravel DebugBar". Contact your computer or network administrator for assistance".

I've read some issues on the Apple Dev Forums but it's the first time I've hit this problem on Big Sur.

Also I've been using HELO and TINKERWELL without issues.

**Comment by kyrylokulyhin** [comment]
@neamtua I think you went for `zip` version. I had the same problem. Fixed by downloading `dmg`.

**Comment by neamtua** [comment]
> Fixed by downloading `dmg`

You're right. That worked. Thank you.
