### ISSUE TITLE
Laravel Homestead

### ISSUE THREAD

**Issue by dqfan2012** [beyondcode/laravel-debugbar-companion#9]
Any advice for getting this to work with Laravel homestead?

I'm running Laravel Homestead in a VMWare. I've reconfigured the default IP address to fall within the range of my VMWare virtual network (192.168.5.1-192.168.5.255) so that when I type http://site.test into the address bar I can actually access it (and I don't have to access it using the IP address). I have everything working. I even have a remote connection to postgresql working. However, nothing I try gets the socket open between Laravel homestead and the app. (I've even tried the port forwarding feature in the Homestead.yaml file).

How I'm running the app: I've cloned the repo and run yarn electron:serve from the master branch (if that helps).

**Comment by dqfan2012** [comment]
Apparently, I needed to send the host port "2304" to a guest port within the VM. Then set the hostname in the debugbar config to the IP address of my host machine. That's interesting. I'm closing with this comment, but it'll be here for anyone else that might need help getting this to work.

**Comment by devlob** [comment]
@dqfan2012 thank you for the instructions, but can you show us your Homesteaad.yaml file?

Did you have to do any modifications to the electron app in terms of source code or did you just change the port number in the app?

Maybe include your config/debugbar.php file as well or just the storage settings.
